seed_everything: 6247
model:
  class_path: PCT_Cls
  init_args:
    submodel: pct
    outputNr: 60
    run_name: L1_originalDS_LR0.0001
    pkl_path: original1024_dataset.pkl
    pretrained: False
    only_last_layer: False
    ckpt_path:
    loss_func:
      class_path: torch.nn.L1Loss
      init_args:
        reduction: mean
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0001
data:
  class_path: src.pct_dataModule.Back_DataModule
  init_args:
    root_dir: /cluster/apps/ethsec/ifb_lmb/PointCloudTransformer/data/data_30
    train_per: 0.8
    test_per: 0.1
    batch_size: 64
    numWorkers: 4
trainer:
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: logs
      name: model_v1
      log_graph: True
      default_hp_metric: False
  callbacks:
    class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      save_top_k: 2
      monitor: loss/val
      mode: min
      filename: pct-epoch={epoch:02d}-val_loss={loss/val:.2f}
      auto_insert_metric_name: False
  max_epochs: 1000