seed_everything: 6247
model:
  class_path: ConvNets
  init_args:
    outputNr: 30
    run_name: smoothL1_test
    pretrained: False
    ckpt_path:
    only_last_layer: False
    pkl_path: originalDataset.pkl
    network: densenet
    loss_func:
      class_path: torch.nn.SmoothL1Loss
      init_args:
        reduction: mean
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
data:
  root_dir: /home/siri/PycharmProjects/msc-sirirueegg-sceML/ConvNets/data/new_test_dataset
  train_per: 0.8
  test_per: 0.1
  batch_size: 8
  numWorkers: 4
trainer:
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: logs
      name: model_v1
      log_graph: True
      default_hp_metric: False
  callbacks:
    class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      save_top_k: 2
      monitor: loss/val
      mode: min
      filename: ConvNets-epoch={epoch:02d}-val_loss={loss/val:.6f}
      auto_insert_metric_name: False
  max_epochs: 700

